/*
Although the inflected forms for most nouns can be generated according to a set of rules,
that's too complicated to implement at this time.  Instead, just store the different forms.
 */

const NDictOb = {
	america:   {inf:{s:'america'}, proper:true},
	arctic:    {inf:{s:'arctic'}, proper:true},
	bakery:    {inf:{s:'bakery'}},
	ball:      {inf:{s:'ball'}},
	bathroom:  {inf:{s:'bathroom'}},
	bed:       {inf:{s:'bed'}},
	blessing:  {inf:{s:'blessing',p:'blessings'}},
	box:       {inf:{s:'box'}},
	bow:       {inf:{s:'bow'}},
	bump:      {inf:{s:'bump'}},
	book:      {inf:{s:'book'}},
	car:       {inf:{s:'car'}},
	cat:       {inf:{s:'cat'}},
	cake:      {inf:{s:'cake'}},
	child:     {inf:{s:'child',p:'children',sg:'child\'s',pg:'children\'s'}},
	coach:     {inf:{s:'coach'}},
	constitution: {inf:{s:'constitution'}},
	cup:       {inf:{s:'cup'}},
	day:       {inf:{s:'day'}},
	defense:   {inf:{s:'defense'}},
	dish:      {inf:{s:'dish'}},
	doctor:    {inf:{s:'doctor'}},
	dog:       {inf:{s:'dog'}},
	fan:       {inf:{s:'fan'}},
	fear:      {inf:{s:'fear'}},
	forest:    {inf:{s:'forest'}},
	fox:       {inf:{s:'fox'}},
	fish:      {inf:{s:'fish'}},
	fun:       {inf:{s:'fun'}},
	game:      {inf:{s:'game'}},
	gown:      {inf:{s:'gown'}},
	hall:      {inf:{s:'hall'}},
	hat:       {inf:{s:'hat'}},
	hand:      {inf:{s:'hand'}},
	head:      {inf:{s:'head'}},
	house:     {inf:{s:'house'}},
	hook:      {inf:{s:'hook'}},
	job:       {inf:{s:'job'}},
	justice:   {inf:{s:'justice'}},
	kite:      {inf:{s:'kite'}},
	liberty:   {inf:{s:'liberty'}},
	look:      {inf:{s:'look'}},
	man:       {inf:{s:'man'}},
	mat:       {inf:{s:'mat'}},
	mess:      {inf:{s:'mess'}},
	mother:    {inf:{s:'mother'}},
	minute:    {inf:{s:'minute'}},
	milk:      {inf:{s:'milk'}},
	net:       {inf:{s:'net'}},
	pat:       {inf:{s:'pat'}},
	person:    {inf:{s:'person',p:'people'}},
	plaything: {inf:{s:'plaything'}},
	posterity: {inf:{s:'posterity'}},
	pot:       {inf:{s:'pot'}},
	rake:      {inf:{s:'rake'}},
	sun:       {inf:{s:'sun'}},
	ship:      {inf:{s:'ship'}},
	state:     {inf:{s:'state',p:'states'}},
	string:    {inf:{s:'string'}},
	tail:      {inf:{s:'tail'}},
	tip:       {inf:{s:'tip'}},
	thief:     {inf:{s:'thief'}},
	thing:     {inf:{s:'thing'}},
	tranquility: {inf:{s:'tranquility'}},
	trick:     {inf:{s:'trick'}},
	top:       {inf:{s:'top'}},
	union:     {inf:{s:'union'}},
	wall:      {inf:{s:'wall'}},
	way:       {inf:{s:'way'}},
	welfare:   {inf:{s:'welfare'}}
}

export default NDictOb
